name: blueprint_app
description: A mobile app for generating 2D floor plans and connecting users with nearby vendors.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  provider: ^6.1.2
  cached_network_image: any
  google_fonts: any
  permission_handler: any
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: any
  geolocator: ^13.0.2
  url_launcher: ^6.1.14
  firebase_storage: ^12.4.4
  image_picker: ^1.0.7
  google_sign_in: ^6.3.0
  cupertino_icons: ^1.0.8
  siri_wave: ^2.3.0
  speech_to_text: ^7.0.0
  flutter_svg: ^1.0.3
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  build_runner: ^2.4.14

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/newproject.svg
    - assets/icons/professionals.svg
    - assets/icons/gallery.svg     # ✅ Added Community Gallery icon
    - assets/animations/landingscreenanimation.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
