// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'Reconfigure this by running FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt3bbNDvq0cFfWuwgWyjj-SXr-nzJFvgM',
    appId: '1:771359169632:web:9d6fe5b552af93d34f3705',
    messagingSenderId: '771359169632',
    projectId: 'blueprint-9695e',
    authDomain: 'blueprint-9695e.firebaseapp.com',
    databaseURL: 'https://blueprint-9695e-default-rtdb.firebaseio.com',
    storageBucket: 'blueprint-9695e.firebasestorage.app',
    measurementId: 'G-WHYXY97Z2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdIs8r7LZErSOgKh3_1GhjgzygXzkv40',
    appId: '1:771359169632:android:45cdd742d3db6b434f3705',
    messagingSenderId: '771359169632',
    projectId: 'blueprint-9695e',
    databaseURL: 'https://blueprint-9695e-default-rtdb.firebaseio.com',
    storageBucket: 'blueprint-9695e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYwsG2mgl6D-BWqAIGfsSm3pTU6hDHycY',
    appId: '1:771359169632:ios:8eade0782a570bb74f3705',
    messagingSenderId: '771359169632',
    projectId: 'blueprint-9695e',
    databaseURL: 'https://blueprint-9695e-default-rtdb.firebaseio.com',
    storageBucket: 'blueprint-9695e.firebasestorage.app',
    iosClientId: '771359169632-j4t07ulmt3osd8rbfqpth39fvhd2lkk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bpFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYwsG2mgl6D-BWqAIGfsSm3pTU6hDHycY',
    appId: '1:771359169632:ios:8eade0782a570bb74f3705',
    messagingSenderId: '771359169632',
    projectId: 'blueprint-9695e',
    databaseURL: 'https://blueprint-9695e-default-rtdb.firebaseio.com',
    storageBucket: 'blueprint-9695e.firebasestorage.app',
    iosClientId: '771359169632-j4t07ulmt3osd8rbfqpth39fvhd2lkk2.apps.googleusercontent.com',
    iosBundleId: 'com.example.bpFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt3bbNDvq0cFfWuwgWyjj-SXr-nzJFvgM',
    appId: '1:771359169632:web:d5f6eb1f0b6231484f3705',
    messagingSenderId: '771359169632',
    projectId: 'blueprint-9695e',
    authDomain: 'blueprint-9695e.firebaseapp.com',
    databaseURL: 'https://blueprint-9695e-default-rtdb.firebaseio.com',
    storageBucket: 'blueprint-9695e.firebasestorage.app',
    measurementId: 'G-FRS7JJF6FR',
  );

}